version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Simular build
          command: |
            echo "Construyendo aplicación..."
            mkdir output
            echo "artifact generado correctamente" > output/app.txt

      - store_artifacts:
          path: output
          destination: build-artifacts

workflows:
  build-workflow:
    jobs:
      - build
